-- Enable required PostgreSQL extensions
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;
CREATE EXTENSION IF NOT EXISTS pgrouting;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Australian base schemas
CREATE SCHEMA IF NOT EXISTS abs;
CREATE SCHEMA IF NOT EXISTS gnaf;
CREATE SCHEMA IF NOT EXISTS osm;
